## PostgreSQL base template — extensible foundation
##
## Use directly via `include:` or cross-repo via `extends:`.
## No ports, no init sidecars — just the core service.

services:

  postgres:
    image: postgres:16
    container_name: soa-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

volumes:
  postgres-data:
    name: postgres-profile-${SEED_PROFILE:-small}
