packages:
  # Apps by runtime tier
  - 'apps/web/*'
  - 'apps/node/*'
  - 'apps/node/*/trpc-types'
  - 'apps/node/*/tgql-types'
  - 'apps/core/*'
  # Legacy - will be removed after migration
  - 'apps/projects/*'
  # Packages by runtime tier
  - 'packages/web/*'
  - 'packages/node/*'
  - 'packages/core/*'
  # Build tools
  - 'build-tools/*'
  # Infrastructure templates
  - 'infra'
