// Export generated types from generated directory
export * from '../generated/types/index.js';

// Note: The schema runtime functions (buildAppSchema, getSchemaSDL, resolvers) 
// are not currently generated by tgql-codegen. This would require adding a 
// Schema Runtime Generator to the tgql-codegen package.
// For now, consumers should manually create these if needed.