// Re-export the generated static router and its types
export { staticAppRouter as appRouter, type AppRouter } from '../generated/router.js';

// Export Zod schemas for runtime validation from generated directory
export * from '../generated/schemas/index.js';

// Export pure TypeScript types generated by zod2ts (these don't require zod at runtime)
export * from '../generated/types/index.js'; 