/**
 * `build-clean` — remove stale build output so a cold start rebuilds from scratch (soa#cold-start).
 *
 * The native prep pass (`prep.ts`) has a FRESH-SKIP: a repo with both `node_modules` AND a built
 * `dist/` is skipped entirely (see `BaseCommand.getPrepFreshCheck` / `isRepoBuilt`). That is right
 * for the everyday `up` — but it means a STALE `dist/` (old code from a prior branch) is happily
 * reused. A cold start's whole point is a guaranteed-clean build, so it first REMOVES the build
 * output; the very next `up` then sees the repo as "not built" and rebuilds it.
 *
 * TWO depths, matching the flags:
 *   - default (`clean`): `rm -rf` every `dist/` under `packages/node/` + `apps/node/`. These are the
 *     dirs `isRepoBuilt` checks, so removing them DEFEATS the fresh-skip and forces `pnpm build`.
 *     Fast (seconds) and safe (regenerated by the build).
 *   - `--reinstall`: ALSO `rm -rf` the repo-root `node_modules`, forcing a full `pnpm install`
 *     before the build. Slow (minutes, per repo) — opt-in only.
 *
 * The scan roots (`distScanRoots`) + reinstall targets (`reinstallTargets`) are PURE and
 * unit-tested; the discovery + `rm -rf` live behind the injectable `BuildCleaner` seam
 * (`makeRealBuildCleaner()` is the only place a real `rm -rf` runs). IO stays in `src/runtime/**`.
 */

import { readdirSync, rmSync, statSync } from 'node:fs';
import { join } from 'node:path';

/** The node-workspace roots whose per-package `dist` a build produces (mirrors base-command `NODE_WORKSPACE_DIRS`). */
export const NODE_WORKSPACE_DIRS = ['packages/node', 'apps/node'] as const;

/** PURE: the dirs to scan for immediate `<pkg>/dist` children in a repo. */
export function distScanRoots(repoRoot: string): string[] {
  const root = repoRoot.replace(/\/+$/, '');
  return NODE_WORKSPACE_DIRS.map((d) => join(root, d));
}

/** PURE: the extra targets a `--reinstall` removes (repo-root `node_modules`). */
export function reinstallTargets(repoRoot: string): string[] {
  const root = repoRoot.replace(/\/+$/, '');
  return [join(root, 'node_modules')];
}

/** What a build-clean removed from one repo. */
export interface BuildCleanResult {
  /** Absolute `dist/` dirs removed. */
  removedDist: string[];
  /** Absolute `node_modules` dirs removed (only under `--reinstall`). */
  removedModules: string[];
}

/** The injectable build-clean seam. `clean` removes a repo's build output (best-effort). */
export interface BuildCleaner {
  clean(repoRoot: string, opts: { reinstall: boolean }): Promise<BuildCleanResult>;
}

/** Injectable low-level fs deps of the real build-cleaner (defaulted to real IO). */
export interface RealBuildCleanerDeps {
  /** List a dir's entries. Default `fs.readdirSync`; `[]` on any error. */
  listDir?: (p: string) => string[];
  /** Is a path a directory? Default `fs.statSync(p).isDirectory()` (folds an error to false). */
  isDir?: (p: string) => boolean;
  /** `rm -rf` a path. Default `fs.rmSync(p,{recursive,force})` (best-effort — swallows errors). */
  remove?: (p: string) => void;
}

/**
 * The production build-cleaner: for each node-workspace root, remove every immediate
 * `<pkg>/dist`; under `--reinstall`, also remove the repo-root `node_modules`. Every op is
 * best-effort (a missing dir / permission error is a no-op) — a dir we can't remove is
 * reported as not-removed, never an abort.
 */
export function makeRealBuildCleaner(deps: RealBuildCleanerDeps = {}): BuildCleaner {
  const listDir =
    deps.listDir ??
    ((p: string): string[] => {
      try {
        return readdirSync(p);
      } catch {
        return [];
      }
    });
  const isDir =
    deps.isDir ??
    ((p: string): boolean => {
      try {
        return statSync(p).isDirectory();
      } catch {
        return false;
      }
    });
  const remove =
    deps.remove ??
    ((p: string): void => {
      rmSync(p, { recursive: true, force: true });
    });

  /** Remove `p` if it's a dir; return true iff it existed and was removed. */
  function removeIfDir(p: string): boolean {
    if (!isDir(p)) return false;
    try {
      remove(p);
      return true;
    } catch {
      return false;
    }
  }

  return {
    async clean(repoRoot: string, opts: { reinstall: boolean }): Promise<BuildCleanResult> {
      const removedDist: string[] = [];
      for (const scanRoot of distScanRoots(repoRoot)) {
        for (const pkg of listDir(scanRoot)) {
          const dist = join(scanRoot, pkg, 'dist');
          if (removeIfDir(dist)) removedDist.push(dist);
        }
      }
      const removedModules: string[] = [];
      if (opts.reinstall) {
        for (const nm of reinstallTargets(repoRoot)) {
          if (removeIfDir(nm)) removedModules.push(nm);
        }
      }
      return { removedDist, removedModules };
    },
  };
}
