/**
 * Native `--tunnel` prep IO (Phase 2, saga-ed/soa#214) — the two host-touching
 * steps up.sh's `--tunnel` resolution block does BEFORE any launch line runs, so
 * the per-service `tunnel_env` overlay has correct values:
 *
 *  1. `resolveTunnelMoniker` — run the VENDORED `tunnel.sh moniker` and capture
 *     its stdout (up.sh `TUNNEL_MONIKER=$("$SCRIPT_DIR/tunnel.sh" moniker)`). The
 *     moniker prompt (first run) talks on the TTY, so stdin+stderr are inherited
 *     while stdout is piped — exactly up.sh's `$()` capture with stderr on the TTY.
 *     `<moniker>.<VMS_BASE>` is the tunnel domain the overlay flips every browser
 *     URL to.
 *
 *  2. `generateTunnelFleetConfig` — render `rtsm-fleet-tunnel.json` from the base
 *     `rtsm-fleet-local.json`, swapping `nodes.local.endpoint` to the tunnel host
 *     so rtsm discovery returns a browser-reachable URL (up.sh's node -e block).
 *     Best-effort: on any failure rtsm-api keeps its local fleet (remote discovery
 *     falls back), never aborting the bring-up.
 *
 * Both live in `runtime/**` (OS-touching); the command wires them behind seams so
 * the unit tests inject fakes and never spawn tunnel.sh or read the fleet file.
 */

import { spawn } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

/**
 * Run `<vendorTunnelSh> moniker`, capturing trimmed stdout (the moniker). stdin +
 * stderr inherit the user's TTY so the first-run bootstrap prompt + any progress
 * still reach the terminal, matching up.sh's stderr-on-TTY `$()` capture. Rejects
 * on a non-zero exit / spawn error (the command turns it into a hard error, as
 * up.sh does — "could not resolve a moniker").
 */
export function resolveTunnelMoniker(vendorTunnelSh: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const child = spawn(vendorTunnelSh, ['moniker'], {
      cwd: dirname(vendorTunnelSh),
      stdio: ['inherit', 'pipe', 'inherit'],
    });
    let out = '';
    child.stdout?.on('data', (d: Buffer) => {
      out += d.toString();
    });
    child.on('error', reject);
    child.on('close', (code) => {
      const moniker = out.trim();
      if (code === 0 && moniker) resolve(moniker);
      else reject(new Error(`tunnel.sh moniker failed (exit ${code ?? 'signal'})`));
    });
  });
}

/**
 * Render `rtsm-fleet-tunnel.json` from `localFleetPath`, swapping the single node's
 * `endpoint` to the browser-visible tunnel host (`rtsm.<tunnelDomain>`, bare — the
 * rtsm-client composes the scheme from its bootstrap URL). Returns the written path
 * on success, or `null` on any failure (best-effort; caller keeps the local fleet).
 */
export function generateTunnelFleetConfig(opts: {
  localFleetPath: string;
  outPath: string;
  tunnelDomain: string;
}): string | null {
  try {
    const cfg = JSON.parse(readFileSync(opts.localFleetPath, 'utf8')) as {
      nodes?: { local?: { endpoint?: string } };
      _comment?: string;
    };
    if (!cfg.nodes?.local) return null;
    cfg._comment =
      'GENERATED by saga-stack up --tunnel from rtsm-fleet-local.json — endpoint swapped to the tunnel host.';
    cfg.nodes.local.endpoint = `rtsm.${opts.tunnelDomain}`;
    writeFileSync(opts.outPath, `${JSON.stringify(cfg, null, 4)}\n`);
    return opts.outPath;
  } catch {
    return null;
  }
}
