## Redis base template — extensible foundation
##
## Use directly via `include:` or cross-repo via `extends:`.
## No ports — just the core service.

services:

  redis:
    image: redis:7-alpine
    container_name: soa-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
    name: redis-data
