import { z } from 'zod';
import { TypeGenerationError } from './types.js';

export interface TypeGeneratorOptions {
  name?: string;
  typePrefix?: string;
  includeUtils?: boolean;
}

export class TypeGenerator {
  private async loadZodToTs() {
    try {
      // Try standard import first (works in vitest with alias)
      const zodToTsModule = await import('zod-to-ts');
      return {
        zodToTs: zodToTsModule.zodToTs,
        createTypeAlias: zodToTsModule.createTypeAlias,
        printNode: zodToTsModule.printNode
      };
    } catch (error) {
      try {
        // Fallback to direct path for PNPM workspace issues (works with tsx)
        const path = await import('path');
        const fs = await import('fs');
        const { fileURLToPath } = await import('url');
        
        // Get current directory in ES module context
        const currentFile = fileURLToPath(import.meta.url);
        const currentDir = path.dirname(currentFile);
        
        // Try multiple possible paths for the workspace structure
        const possiblePaths = [
          path.resolve(currentDir, '../../node_modules/.pnpm/zod-to-ts@1.2.0_typescript@5.8.3_zod@3.25.67/node_modules/zod-to-ts/dist/index.cjs'),
          path.resolve(currentDir, '../../../node_modules/.pnpm/zod-to-ts@1.2.0_typescript@5.8.3_zod@3.25.67/node_modules/zod-to-ts/dist/index.cjs'),
          path.resolve(currentDir, '../../../../node_modules/.pnpm/zod-to-ts@1.2.0_typescript@5.8.3_zod@3.25.67/node_modules/zod-to-ts/dist/index.cjs')
        ];
        
        let zodToTsPath = null;
        for (const testPath of possiblePaths) {
          if (fs.existsSync(testPath)) {
            zodToTsPath = testPath;
            break;
          }
        }
        
        if (!zodToTsPath) {
          throw new Error(`Could not find zod-to-ts module in any of the expected paths: ${possiblePaths.join(', ')}`);
        }
        
        // Use createRequire to load CommonJS module from ES module context
        const { createRequire } = await import('module');
        const require = createRequire(import.meta.url);
        const { zodToTs, createTypeAlias, printNode } = require(zodToTsPath);
        return { zodToTs, createTypeAlias, printNode };
      } catch (fallbackError) {
        throw new Error(`Failed to load zod-to-ts module: ${error.message}. Fallback also failed: ${fallbackError.message}`);
      }
    }
  }

  async generateType(schema: z.ZodSchema, typeName: string, options: TypeGeneratorOptions = {}): Promise<string> {
    try {
      const { zodToTs, createTypeAlias, printNode } = await this.loadZodToTs();
      const { node } = zodToTs(schema, typeName);
      const typeAlias = createTypeAlias(node, typeName);
      const typeDefinition = printNode(typeAlias);

      return this.formatTypeDefinition(typeDefinition, typeName);
    } catch (error) {
      throw new TypeGenerationError(
        `Failed to generate type for ${typeName}: ${error instanceof Error ? error.message : String(error)}`
      );
    }
  }

  private formatTypeDefinition(typeDefinition: string, typeName: string): string {
    return `// Generated by zod2ts using zod-to-ts
// Do not edit manually

${typeDefinition}
`;
  }
}
