/**
 * Netscape cookie-jar serialization (M11 — the curl-half of up.sh's login_user).
 *
 * up.sh mints a headless session with `curl … -c "$COOKIE_JAR"`, which writes the
 * captured `Set-Cookie`s (iam_session JWT + iam_refresh) as a Netscape cookie file
 * (`$STATE/cookies.txt`) that headless harnesses (curl `--cookie`, Playwright
 * `storageState`) then read. This module ports the two PURE halves of that:
 *   - `parseSetCookie` — a single `Set-Cookie` header string → a structured cookie,
 *   - `toNetscapeJar`  — those cookies → the exact Netscape-format text curl writes,
 * so the runtime seam only has to POST + write bytes. No IO here (core stays pure).
 *
 * FORMAT (curl's `# Netscape HTTP Cookie File`): one TAB-separated row per cookie —
 *   <domain> <includeSubdomains> <path> <secure> <expires> <name> <value>
 * An HttpOnly cookie is prefixed with `#HttpOnly_` on the domain field (curl's own
 * convention) — iam_session/iam_refresh are HttpOnly, so both carry that prefix.
 */

/** A single parsed `Set-Cookie` (the fields the Netscape jar needs). */
export interface ParsedCookie {
  name: string;
  value: string;
  /** The cookie's domain (no leading dot). Defaults to the request host when no `Domain=` attr. */
  domain: string;
  /** True when there was NO explicit `Domain=` attr (host-only ⇒ Netscape flag FALSE). */
  hostOnly: boolean;
  path: string;
  secure: boolean;
  httpOnly: boolean;
  /** Expiry as epoch SECONDS; `0` = a session cookie (curl writes 0). */
  expires: number;
}

/**
 * Parse ONE `Set-Cookie` header value into a `ParsedCookie`, defaulting domain to
 * `requestHost` and path to `/` (the cookie RFC defaults). Returns `null` for a
 * malformed header (no `name=value` first pair) so the caller can skip it. Pure.
 */
export function parseSetCookie(header: string, requestHost: string): ParsedCookie | null {
  const segments = header.split(';');
  const first = segments.shift();
  if (first === undefined) return null;
  const eq = first.indexOf('=');
  if (eq < 0) return null;
  const name = first.slice(0, eq).trim();
  const value = first.slice(eq + 1).trim();
  if (name === '') return null;

  let domain = requestHost;
  let hostOnly = true;
  let path = '/';
  let secure = false;
  let httpOnly = false;
  let expires = 0;

  for (const attr of segments) {
    const [rawKey = '', ...rest] = attr.split('=');
    const key = rawKey.trim().toLowerCase();
    const v = rest.join('=').trim();
    if (key === 'domain' && v !== '') {
      domain = v.replace(/^\./, '');
      hostOnly = false;
    } else if (key === 'path' && v !== '') {
      path = v;
    } else if (key === 'secure') {
      secure = true;
    } else if (key === 'httponly') {
      httpOnly = true;
    } else if (key === 'max-age') {
      const n = Number.parseInt(v, 10);
      // Max-Age wins over Expires (RFC 6265 §5.3) — resolve to an absolute epoch.
      if (Number.isFinite(n)) expires = Math.floor(Date.now() / 1000) + n;
    } else if (key === 'expires' && expires === 0) {
      const t = Date.parse(v);
      if (!Number.isNaN(t)) expires = Math.floor(t / 1000);
    }
  }

  return { name, value, domain, hostOnly, path, secure, httpOnly, expires };
}

/** The header curl writes atop a `# Netscape HTTP Cookie File`. */
const NETSCAPE_HEADER =
  '# Netscape HTTP Cookie File\n' +
  '# https://curl.se/docs/http-cookies.html\n' +
  '# This file was generated by saga-stack. Edit at your own risk.\n\n';

/**
 * Serialize cookies to the exact Netscape jar text curl's `-c` writes: a header
 * then one TAB-separated row per cookie. A host-only cookie writes its bare host
 * with `includeSubdomains=FALSE`; a `Domain=`-scoped cookie writes `.<domain>`
 * with `TRUE`. HttpOnly cookies (iam_session/iam_refresh) get curl's `#HttpOnly_`
 * domain prefix. Pure.
 */
export function toNetscapeJar(cookies: ParsedCookie[]): string {
  const rows = cookies.map((c) => {
    const domainField = c.hostOnly ? c.domain : `.${c.domain}`;
    const includeSub = c.hostOnly ? 'FALSE' : 'TRUE';
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const prefix = c.httpOnly ? '#HttpOnly_' : '';
    return `${prefix}${domainField}\t${includeSub}\t${c.path}\t${secure}\t${c.expires}\t${c.name}\t${c.value}`;
  });
  return NETSCAPE_HEADER + (rows.length > 0 ? `${rows.join('\n')}\n` : '');
}
