// Generated by zod2ts
// Do not edit manually

export type UserProfile = {
  userId: string;
  bio: string | undefined;
  avatar: string | undefined;
  preferences: {
    theme: any;
    notifications: any;
  };
};
