## MySQL base template — extensible foundation
##
## Use directly via `include:` or cross-repo via `extends:`.
## No ports, no init sidecars — just the core service.

services:

  mysql:
    image: mysql:8.0
    container_name: soa-mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s

volumes:
  mysql-data:
    name: mysql-profile-${SEED_PROFILE:-small}
